version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: retell-backend
    ports:
      - "8000:8000"
    environment:
      - RETELL_API_KEY=${RETELL_API_KEY}
      - PORT=8000
      - ENVIRONMENT=production
    volumes:
      - ./backend/.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - retell-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8000
    container_name: retell-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - retell-network

networks:
  retell-network:
    driver: bridge
    name: retell-network

# To run the application:
# 1. Copy .env.example to .env in the backend directory
# 2. Add your RETELL_API_KEY to the .env file
# 3. Run: docker-compose up --build
#
# The application will be available at:
# - Frontend: http://localhost:3000
# - Backend API: http://localhost:8000
# - API Docs: http://localhost:8000/docs
#
# To run in detached mode: docker-compose up -d --build
# To stop: docker-compose down
# To rebuild: docker-compose up --build --force-recreate