version: '3.8'

services:
  backend:
    build: ./backend
    container_name: retell-backend
    ports:
      - "8000:8000"
    environment:
      - RETELL_API_KEY=${RETELL_API_KEY}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: retell-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: retell-network
