version: '3.8'

services:
  backend:
    build: ./backend
    container_name: retell-backend
    ports:
      - "8000:8000"
    environment:
      - RETELL_API_KEY=${RETELL_API_KEY}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: retell-frontend
    ports:
      - "3000:3000"
    environment:
      # Point the React app to the backend service name (Docker DNS)
      - REACT_APP_BACKEND_URL=http://retell-network:8000
      - REACT_APP_DEBUG=${FRONTEND_DEBUG:-false}
    volumes:
      # Mount source for rapid iteration (hot reload) if you switch Dockerfile to dev mode
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: retell-network
